### ISSUE TITLE
Issue with loading sukaku grid

### ISSUE THREAD

**Issue by 1to9only** [SudokuMonster/SukakuExplainer#18] opened 2019-08-17 07:11 UTC
There is a reasonable expectation that:
a Load followed immediately by a Saved, the saved file would exactly match the loaded file,
a Save followed by a Load would show the same grid state displayed.

There is no sukaku save option. yet!

However, loading this sukaku grid recently discussed at forum.enjoysudoku.com shows the issue:
```
+----------------------+----------------------+----------------------+
| 9      8      12345  | 7      346    1246   | 1234   145    235    |
| 7      1235   12345  | 12348  3489   12489  | 6      14589  23589  |
| 1234   123    6      | 12348  5      12489  | 123478 14789  23789  |
+----------------------+----------------------+----------------------+
| 1268   4      129    | 168    678    5      | 278    3      26789  |
| 12368  1236   7      | 9      3468   1468   | 5      468    268    |
| 3568   3569   359    | 3468   2      4678   | 478    46789  1      |
+----------------------+----------------------+----------------------+
| 123456 123567 8      | 56     467    2467   | 9      1567   3567   |
| 2356   235679 2359   | 2568   1      26789  | 378    5678   4      |
| 1456   15679  1459   | 4568   46789  3      | 178    2      5678   |
+----------------------+----------------------+----------------------+
```
All cells are displayed as containing clues, it's rating is ED=12.0/1.2/1.2.
The cells with single clues are givens, it's rating is then ED=12.0/12.0/11.8.
Note: The issue also exists in the Aug 5 SE.

**Comment by dobrichev** [comment] 2019-08-17 07:51
From the same beginning I found strange trend 1.0 rating steps to be postponed. Looks like a bug in old code that becomes visible solving sukaku. But I could be wrong.
The variations of Solver.rebuildPotentialValues() and their usage are a possible causes.

**Comment by SudokuMonster** [comment] 2019-08-17 21:53
I don't think that this is a bug. The puzzle shows candidates! Some cells show a single candidate. This single candidate is both (a hidden single and a naked single) and will be uncovered as a hidden single as that technique is ranked lowest. If you paste a pencilmark grid of a vanilla sudoku then you will have a series of hidden singles before the puzzle starts (similar to the example above)

The solution to this is to check these (single candidate cells) when the pencilmark grid is pasted/processed. If they are both a hidden and naked single then they should be pasted as an uncovered cell rather than a candidate.

**Comment by dobrichev** [comment] 2019-08-18 00:26
When the solving engine's must as close as possible reproduce human solver's logic, the Naked Single elimination becomes the least difficult move once the solver is switching to pencilmark representation of the puzzle.
There are reasons this never to be done for vanilla sudoku - different human solvers would switch to pencilmarks at different stage, etc.
But for pencilmark-only sudoku the solver IS starting from pencilmarks by definition.
A cheap fix could be **doing Naked Singles eliminations on load**, before entering the elimination loop.
My bet is that even the worst human solver wouldn't spend 81 steps to solve a given solution grid to the same solution grid.

**Comment by SudokuMonster** [comment] 2019-08-18 00:57
Quick and dirty solution (basically the 2nd option in my last comment)
```
        for (String pattern : sukakuLineFormat)
        {
        	Matcher result = java.util.regex.Pattern.compile(pattern).matcher(singleLine);
            if (result.find())
            {
            	String line = result.group("key");
                for (int y = 0; y < 9; y++)
                {
                    for (int x = 0; x < 9; x++)
                    {
                    	HashSet<Integer> possible = new HashSet<Integer>();
                        for (int i = 0; i < 9; i++)
                        {
                            char ch = line.charAt(i + x * 9 + y * 81);
                            if (ch >= '1' && ch <= '9')
                                possible.add(ch - '0');
                        }                       
						if (possible.size() == 1)
						{	
							for (int i = 1; i <= 9; i++)
							{
								if (possible.contains(i))
								{
									grid.setCellValue(x, y, i);
									break;
								}
							}
							continue;
						}
                        Cell cell = grid.getCell(x, y);
						for (int i = 1; i <= 9; i++)
                        {
                            if (!possible.contains(i))
                                cell.removePotentialValue(i);
                        }
                    }
                }
               
                return RES_OK;
            }
        }
```
AND
```
        for (String part : parts) {
            Cell cell = grid.getCell(x, y);
           
            HashSet<Integer> possible = new HashSet<Integer>();
            for (char ch : part.toCharArray()) {
                if (ch >= '1' && ch <= '9')
                    possible.add(ch - '0');
            }
			if (possible.size() == 1)
			{	
				for (int i = 1; i <= 9; i++)
				{
					if (possible.contains(i))
					{
						grid.setCellValue(x, y, i);
						break;
					}
				}
			}
			else
			{
				for (int i = 1; i <= 9; i++)
				{
					if (!possible.contains(i))
						cell.removePotentialValue(i);
				}
			}
            x++;
            if (x == 9) {
                y++;
                x = 0;
                if (y == 9)
                    break; //ignore if more than 81 found
            }
        }
```

**Comment by 1to9only** [comment] 2019-08-18 08:53
![rxusEHx](https://user-images.githubusercontent.com/53971101/63222261-79dc0780-c19d-11e9-84b1-36e805771f0e.png)
The sukaku in the first post is as pictured, which 999_Springs posted.
What gives? Is it an ED=12.0/1.2/1.2? Or an 12.0/12.0/11.8?

**Comment by SudokuMonster** [comment] 2019-08-18 09:42
@1to9only please read my last 2 replies here. When the Pencilmark grid is read (Vanilla or Sukaku) the engine eliminates possibilities (removePotentialValue) rather than setting cell values (setCellValue). Using setCellValue when pasting single candidate cells solves the problem as I outlined

**Comment by dobrichev** [comment] 2019-08-18 14:13
I just committed a possible fix. Call grid.adjustPencilmarks() immediately after populating the grid.
This reproduces cases 1 and 3 above.
I didn't understand what the proposed in above post code does. Maybe adjustPencilmarks() does the same.

**Comment by SudokuMonster** [comment] 2019-08-18 15:37
I'll share the code when I write it later tonight. It will follow the following principles:
```
For Each cell in the grid
{
 If the cell has one candidate only
 {
   For each peer-cell of that cell // 20 peer cells in sudoku
     If peer cell has the same candidate
       Goto OutOfThisLoop
   grid.setCellValue is the candidate in cell 
 }
 :OutOfThisLoop
}
```

**Comment by SudokuMonster** [comment] 2019-08-19 00:18
Here is the fixed code. Attached is the .jar file with fix implemented. Tested on GUI … Now the puzzle loads and solves from the point of loading. It is a quick and dirty fix … I'm sure you can optimize it better
```
        for (String pattern : sukakuLineFormat)
        {
        	Matcher result = java.util.regex.Pattern.compile(pattern).matcher(singleLine);
            if (result.find())
            {
            	String line = result.group("key");
                for (int y = 0; y < 9; y++)
                {
                    outer:
					for (int x = 0; x < 9; x++)
                    {
                    	HashSet<Integer> possible = new HashSet<Integer>();
                        for (int i = 0; i < 9; i++)
                        {
                            char ch = line.charAt(i + x * 9 + y * 81);
                            if (ch >= '1' && ch <= '9')
                                possible.add(ch - '0');
                        }                       
                        Cell cell = grid.getCell(x, y);
						if (possible.size() == 1)
						{	
							inner:
							for (int i = 1; i <= 9; i++)
							{
								if (possible.contains(i))
								{
									int a = (x / 3) + (y / 3) * 3;
									for (int c = 0; c < 9; c++)
									{
										for (int b = 0; b < 9; b++)
										{
											int d = (b / 3) + (c / 3) * 3;
											if ((c == y || b == x || d == a) && (!(c == y && b == x)))
											{
												for (int e = 1; e <= 9; e++)
												{
													char ch = line.charAt(e + b * 9 + c * 81);
													HashSet<Integer> current = new HashSet<Integer>();
													if (ch >= '1' && ch <= '9')
														current.add(ch - '0');	
													if (current.contains(i))
														break inner;
												}
											}
										}
									}
									grid.setCellValue(x, y, i);
									continue outer; 
								}
							}
						}
						for (int i = 1; i <= 9; i++)
                        {
                            if (!possible.contains(i))
                                cell.removePotentialValue(i);
                        }
                    }
                }
	
                return RES_OK;
            }
        }
```
```
        int y = 0, x = 0;
        for (String part : parts)
		{
			int a = (x / 3) + (y / 3) * 3;
            Cell cell = grid.getCell(x, y);          
            HashSet<Integer> possible = new HashSet<Integer>();
            for (char ch : part.toCharArray())
			{
                if (ch >= '1' && ch <= '9')
                    possible.add(ch - '0');
            }
			if (possible.size() == 1)
			{					
				loop:
				for (int i = 1; i <= 9; i++)
				{
					if (possible.contains(i))
					{
						int c = 0, b = 0;
						for (String spare : parts) {
							int d = (b / 3) + (c / 3) * 3;
							if ((c == y || b == x || d == a) && (!(c == y && b == x)))
							{	
								HashSet<Integer> current = new HashSet<Integer>();
								for (char ch : spare.toCharArray())
								{
									if (ch >= '1' && ch <= '9')
										current.add(ch - '0');
								}
								if (current.contains(i))
									break loop;
							}
							b++;
							if (b == 9) {
								c++;
								b = 0;
								if (c == 9)
									break; //ignore if more than 81 found
							}
						}
						grid.setCellValue(x, y, i);
						break loop;
					}
				}
			}
			for (int i = 1; i <= 9; i++)
			{
				if (!possible.contains(i))
					cell.removePotentialValue(i);
			}
            x++;
            if (x == 9) {
                y++;
                x = 0;
                if (y == 9)
                    break; //ignore if more than 81 found
            }
        }
```
[SukEx_Master_2mergers_Thenfix.zip](https://github.com/SudokuMonster/SukakuExplainer/files/3513739/SukEx_Master_2mergers_Thenfix.zip)

**Comment by dobrichev** [comment] 2019-08-19 06:42
The change looks unnecessarily complicated.
I would suggest resolving the issue in a simplest way as well as it doesn't affect vanilla puzzles.
The framework has design and implementation flaws and doing additional complication in the initialization could quickly lead the project to nowhere.

The change proposed by me resolves all cells with single possibility in their pencilmarks, then on second pass does the direct eliminations, this leaving the board in consistent state but without recursively resolving eventual newly appeared Naked Singles.

The framework flaw directly related to this issue is_public void Cell.setValue(int value)_, where
- the framework expects after resolving the value of a cell all direct eliminations in the seen cells to be applied, but doesn't do this.
- after resolving a cell the framework doesn't clear/reduce the pencilmarks for the same cell.

_public void Cell.setValueAndCancel(int value, Grid targetGrid)_ does both of the above, but calling it in a loop during the initialization could lead in chain of unwanted eliminations.

**Comment by SudokuMonster** [comment] 2019-08-19 07:10
Did I say my solution was great. It was a dirty solution but addresses the issues raised. As mentioned a few replies back there are 2 ways to resolve this problem. One is quick ( your solution and my previous solution). One is ugly and longer but more accurate (the code that I just posted). I’m happy for my code to be modified or replaced to a more efficient or concise way.

The wiki page https://github.com/SudokuMonster/SukakuExplainer/wiki/Loading-Pencilmark-grids-into-Sukaku-explainer-(Test-Puzzles) has the test puzzles to check for this particular problem

**Comment by dobrichev** [comment] 2019-08-19 09:18
Hi @SudokuMonster,
It would cost me resources to fully understand the issue and your patch.
Maybe the same is valid in your understanding of my patch.
Being constructive, I am suggesting to compare the functionalities of both patches and to choose the better, even when they both are dirty.
I am focused on batch processing. The last code in serate doesn't use IO class. I am accepting your change since it doesn't interfere with serate. If you able to spend time in taking a look at this code I am OK. If not, I am OK too.
``` java
    /**
     * Clears potentialValues for cells with value set.
     * First pass sets value for cells having single potential value w/o applying
     * further direct eliminations. Clears potentials of the cells with newly set values.
     * Second pass does direct eliminations.
     */
    public void adjustPencilmarks() {
    	//first pass: apply Naked Single
    	List<Cell> forEliminations = new ArrayList<Cell>();
    	for(int x = 0; x < 9; x++) {
    		for(int y = 0; y < 9; y++) {
    			Cell cell = cells[x][y];
    			if(cell.getValue() != 0) {
    				cell.clearPotentialValues();
    			}
    			else {
    				BitSet values = cell.getPotentialValues();
    				if(values.cardinality() == 1) {
    					cell.setValue(values.nextSetBit(0));
    					cell.clearPotentialValues();
    					forEliminations.add(cell);
    				}
    			}
    		}
    	}
    	//second pass: apply direct eliminations
    	for(Cell cell : forEliminations) {
    		cell.setValueAndCancel(cell.getValue(), this);
    	}
    }
```

**Comment by 1to9only** [comment] 2019-08-19 09:51
I still maintain a version of the Aug 5 SE for personal use. It has separate code for loading sodokus and sukakus. After a sukaku is loaded, my code after refinement is this (I usually go for the shortest solution that works!):
```
// fix naked singles
for (int i = 0; i < 81; i++) {
    Cell cell = grid.getCell(i % 9, i / 9);
    if ( cell.getPotentialValues().cardinality() ==  1 ) {
        int singleclue = cell.getPotentialValues().nextSetBit(0);
        boolean isnakedsingle = true;
        for (Cell housecell : cell.getHouseCells()) {
            if ( housecell.hasPotentialValue(singleclue) ) {
                isnakedsingle = false;
                break;
            }
        }
        if ( isnakedsingle )
        {
            cell.setValue( singleclue);
            cell.getPotentialValues().clear();
        }
    }
}
```
I don't think it can be cut and pasted asis into SukakuExplainer.

**Comment by SudokuMonster** [comment] 2019-08-19 10:13
I can test both GUI and command line late tonight. If @1to9only and / or @dobrichev can link / attach a jar file with their changes then I can use the test puzzles on the wiki page. My code was tested for GUI only. The code that will handle both GUI and command line is the winner!

**Comment by dobrichev** [comment] 2019-08-19 10:22
I removed my comments: the choice isn't technical and my patch isn't a functional equivalent.

**Comment by SudokuMonster** [comment] 2019-08-19 12:02
This was an easy contest

**Comment by dobrichev** [comment] 2019-08-19 12:56
BTW the proposal from @1to9only looks like functional equivalent and is more compact and readable to me.

**Comment by 1to9only** [comment] 2019-08-19 14:15
@SudokuMonster : Are you able to build and test the fix?
I'm currently doing edits in a browser! To build: I'll have to download a zip file, move it to another machine (64bit with jdk-12) and build, maybe do a quick test, copy the SE.jar file to upload. I also don't want to attatch too many files to the project.

**Comment by SudokuMonster** [comment] 2019-08-19 19:12
I’m using the latest JDK and compile using eclipse. I occasionally edit from browser and download the zip file too. I can see that you started a branch @1to9only  which I can try to compile and test tonight.

I will also test my branch “GUI” tonight and report back

Both your codes appear to do a Naked single sweep which is quick, simple and efficient but it will also cause mistakes in the diamond rating (not the overall rating, which will remain correct).

**Comment by 1to9only** [comment] 2019-08-19 19:53
I've changed
`cell.getPotentialValues().clear();`
to a shorter form
`cell.clearPotentialValues();`

I don't use an IDE, and I don't install Java (there is an unzip method for earlier jdks, for jdk-12 there is a zip package). I can run the downloaded 1.2.1.6 SkE.

I build and package from the command line - there errors I'm getting are in the Applet code.

**Comment by SudokuMonster** [comment] 2019-08-19 20:20
I've successfully you latest commit successfully. I've tested the GUI which failed the last 2 puzzles. I haven't tested the command line yet. I have to update the wiki page so that all puzzles have both grid and line formats

**Comment by SudokuMonster** [comment] 2019-08-19 23:11
Initila testing command line processing:
The good news goes to ....... @1to9only 
I tested the following:
```
....56.89..3....89......7....3456..91..........345...9.2.........34.6.....34...8......6..9...4.......3.....9.......8...3..6..9.2.......1.3..67......5....1.3...7..1.........23....8..23.5..8...3456.........7....345......3..6.8...34.6...........9...4..789....5......34...89.234.6..9.234.6..9..34..789..3...7891..........34..78..2.........3...7891..........34....9..34....9..34..789....5......34..7.9.....6......4..789.....6.....34...891.345...9..34....91.345.789..3...789.2.........34..78...3.......2....7.9.2.4....912.4....9.......8.1..4....91....67.9.....67.9....5.......45...91.........2.45...9......7...234....9.....6.....3.....9.......8..23............789.2....789.....6...123.....9....5....1.3.....9...4.......3...7.9123...7..
+-------------------------+-------------------------+-------------------------+
| 5689    69      1       | 4789    2       4789    | 3       459     789     |
| 389     4       238     | 5       3789    6       | 279     1       2789    |
| 7       39      2358    | 3489    1       3489    | 249     2459    6       |
+-------------------------+-------------------------+-------------------------+
| 34569   8       3456    | 23469   349     13459   | 1249    7       1239    |
| 1       369     7       | 23469   349     349     | 8       2349    5       |
| 3459    2       345     | 34789   34789   1345789 | 149     6       139     |
+-------------------------+-------------------------+-------------------------+
| 2       1367    368     | 3789    5       3789    | 1679    39      4       |
| 346     5       346     | 1       3479    2       | 679     8       379     |
| 348     137     9       | 3478    6       3478    | 5       23      1237    |
+-------------------------+-------------------------+-------------------------+
5.2/5.2/3.4
```
Both @1to9only  and @dobrichev rated correctly

But with this:
```
.2345678.1.3.5.7.9.2345.789.234.6.8.1.3.5678912.4.6.8.123.5.7891.3.5.7.912.456.891.3.5.7.9.234.678...3..6...1.3.5.7...2.4.6.8.1.3.5.7891..4......2.4.6.891.3.5.7.91234567.9......78.12.45......3..67891..45..8........89.23..6..........8.12.45.7.9.....67..1.3.567.9..3..6789.2.4.6.8.1.3.5.78..2.4...8.1..4..7891.345.7.9.2.4.6.89123.56.89.2.4.6.8.12.45678.1.3.567.91234.67891.345.7.9..3456.89.2.4.6.8...345.78912.4.6.8.1.3.567.9.23..6..9.2.4.6.8.123.5.7.9.2.4.6.8.1234..7....345.7.9.234.6.8.1.345678912..........45..8.123..6..9.2.4567891.34..7......56.89.23......1..4.67891.3.5.7.912.4.6.89.....6..9123.5.7.9.2.4.6...123...7.9...4..7...234.678.1.3.5.7.912.456.891.3.5.7.912345.789.2.4.6.891234567.9.2.4.678.1.3.567891.3.5.7.9.2345678.,008,0406
+----------------------------+----------------------------+----------------------------+
| 2345678  13579    2345789  | 23468    1356789  12468    | 1235789  13579    1245689  |
| 13579    234678   36       | 1357     2468     135789   | 14       24689    13579    |
| 12345679 78       1245     | 36789    1458     89       | 236      8        124579   |
+----------------------------+----------------------------+----------------------------+
| 67       135679   36789    | 2468     13578    248      | 14789    134579   24689    |
| 1235689  2468     1245678  | 135679   12346789 134579   | 345689   2468     345789   |
| 12468    135679   2369     | 2468     123579   2468     | 12347    34579    23468    |
+----------------------------+----------------------------+----------------------------+
| 13456789 12       458      | 12369    2456789  1347     | 5689     23       146789   |
| 13579    124689   69       | 123579   246      12379    | 47       234678   13579    |
| 1245689  13579    12345789 | 24689    12345679 24678    | 1356789  13579    2345678  |
+----------------------------+----------------------------+----------------------------+
9.4/2.3/2.3
```
@dobrichev  rated it 9.4/1.5/1.5 and @1to9only rated correctly

**Comment by dobrichev** [comment] 2019-08-20 04:30
I can align the master to fixup-naked-singles.... by replacing Grid.adjustPencilmarks() with the code by @1to9only and replacing the 3 copies of the code by calls to this method.
OK to proceed?

**Comment by SudokuMonster** [comment] 2019-08-20 06:52
Fine by me .... I'll check Master after your alignment @dobrichev and @1to9only merger following that. to see if the GUI Pencilmark loading still needs the dirty fix. That would be a minor issue because the important issue is to sort out the command line pencilmark loading.

**Comment by dobrichev** [comment] 2019-08-20 07:12
Done.
To me this is ready for closing.
All pencilmark load clones are in synch, including serate.

**Comment by SudokuMonster** [comment] 2019-08-20 07:13
Great I'll do a quick test to Master Command line and GUI ...

**Comment by SudokuMonster** [comment] 2019-08-20 07:33
@dobrichev @1to9only 
The latest fix is great. I tested the above 2 test cases and worked well.
I tried the following into GUI and failed to load correctly and diamond rating was therefore incorrect (My dirty fix will solve that), But could you try and test it under command line please?
```
 +------------------+-----------------+-----------------+
 |  37   2    6     |  4    5    8    |  9    1    37   | 
 |  78   34   5     |  6    1    9    |  24   23   78   | 
 |  89   49   1     |  2    7    3    |  5    48   6    | 
 +------------------+-----------------+-----------------+
 |  39   7    239   |  5    8    1    |  24   6    34   | 
 |  6    1    4     |  7    3    2    |  8    5    9    | 
 |  5    8    23    |  9    4    6    |  7    23   1    | 
 +------------------+-----------------+-----------------+
 |  4    39   739   |  38   6    5    |  1    78   2    | 
 |  2    6    8     |  1    9    47   |  3    47   5    | 
 |  1    5    37    |  38   2    47   |  6    9    48   | 
 +------------------+-----------------+-----------------+
5.6/5.6/3.2
```

**Comment by dobrichev** [comment] 2019-08-20 07:46
Command line doesn't accept multi-line input.

**Comment by SudokuMonster** [comment] 2019-08-20 08:07
I couldn't find my Multi-line to single line transformer software
It must be on a different machine … Busy today and in the next hour or so will be away for 12 hours

**Comment by 1to9only** [comment] 2019-08-20 08:43
I have problems building the SkE code, see (https://github.com/SudokuMonster/SukakuExplainer/issues/17#issuecomment-522916083).

**Comment by 1to9only** [comment] 2019-08-20 08:51
Command line should work on files with single-line (single puzzle) and files with multi-lines (multiple puzzles) - each puzzle must be single-line, either exactly 81-chars (sudoku) or 729-chars (sukaku).

The fix for naked singles should be applied to sukakus.

**Comment by 1to9only** [comment] 2019-08-20 08:58
I plan to do some extreme testing!

This should load as a nearly completed sukaku:
```
+----------+----------+----------+
| 9  8  1  | 7  3  6  | 2  4  5  |
| 7  3  5  | 4  9  2  | 6  1  8  |
| 4  2  6  | 1  5  8  | 3  9  7  |
+----------+----------+----------+
| 1  4  2  | 6  8  5  | 7  3  9  |
| 3  6  7  | 9  4  1  | 5  8  2  |
| 8  5  9  | 3  2  7  | 4  6  1  |
+----------+----------+----------+
| 2  1  8  | 5  6  4  | 9  7  3  |
| 6  7  3  | 2  1  9  | 8  5  4  |
| 5  9  4  | 8  78 3  | 1  2  6  |
+----------+----------+----------+
```
This should load as a completed sudoku:
```
+-------+-------+-------+
| 9 8 1 | 7 3 6 | 2 4 5 |
| 7 3 5 | 4 9 2 | 6 1 8 |
| 4 2 6 | 1 5 8 | 3 9 7 |
+-------+-------+-------+
| 1 4 2 | 6 8 5 | 7 3 9 |
| 3 6 7 | 9 4 1 | 5 8 2 |
| 8 5 9 | 3 2 7 | 4 6 1 |
+-------+-------+-------+
| 2 1 8 | 5 6 4 | 9 7 3 |
| 6 7 3 | 2 1 9 | 8 5 4 |
| 5 9 4 | 8 7 3 | 1 2 6 |
+-------+-------+-------+
```

**Comment by SudokuMonster** [comment] 2019-08-20 20:01
Hi @1to9only, The grid should load exactly as you loaded it. so the top grid should look exactly as the bottom one. If the GUI or Command line input multi line loader is programmed correctly then all the cells of the Grid will be uncovered EXCEPT r4c5 r9c4 and r9c5. My dirty fix therefore is only needed for the multi line loader until you change the multi line loader with something more suitable in the future. The Single line loader works well for both GUI & Command line input. As you haven't implemented the Multi line sukaku loader from command line yet, my dirty fix for that only shouldn't conflict with what you are doing

I tested the grid
```
..3...7........78........89..3.....9.....6.......5.......4......2.......1.........2.........34........4....9......7..1...............8...3.....9.....6.......5.........6.......5....1.........23.....9...4......23........3...7.9.......8...3...7.....4..........6....2...........5..........7..........9..3....8.1..........3....8.....5....1..............7.........8...3.........4..........6...........9.2..............8.........9..3......1.........2............6.......5.......4..7.....4..7..........9.2.4.........5.....2.4............8.......7..1..........3...........6...1.........23.........4...8......6.......5.....23............78....4..7..........9..3...7........78......6.....34.............91.........2...........5.......4...8.
+-------------+-------------+-------------+
| 37  2   6   | 4   5   8   | 9   1   37  |
| 78  34  5   | 6   1   9   | 24  23  78  |
| 89  49  1   | 2   7   3   | 5   48  6   |
+-------------+-------------+-------------+
| 39  7   239 | 5   8   1   | 24  6   34  |
| 6   1   4   | 7   3   2   | 8   5   9   |
| 5   8   23  | 9   4   6   | 7   23  1   |
+-------------+-------------+-------------+
| 4   39  379 | 38  6   5   | 1   78  2   |
| 2   6   8   | 1   9   47  | 3   47  5   |
| 1   5   37  | 38  2   47  | 6   9   48  |
+-------------+-------------+-------------+
5.6/5.6/3.2
```
GUI failed for the multi line. GUI and command line success for single line

**Comment by 1to9only** [comment] 2019-08-20 21:02
gsf's serate.java came about as a means to rate a batch of sudoku puzzles for the patterns game.
The command line is straight forward - 81-chars it's sudoku, 729-chars it's sukaku. 
I think this should remain.

**Comment by SudokuMonster** [comment] 2019-08-20 21:13
I've just updated only the Multi-line Pencilmark sukaku handler in Master. This would only affect the GUI. If you decide to batch load pencilmark grids via command line then the area that needs to be targeted is the area in sudokuIO.java between:
```
        //Start of Dirty fix for Loading Multiline Sukaku naked singles
        .
        .
        .
        //End of Dirty fix for Loading Multiline Sukaku naked singles
```
I tested Master and it now Loads well with the tested puzzles
This subject if everybody is happy with the fix can be closed now

**Comment by SudokuMonster** [comment] 2019-08-21 09:26
I've updated the Wiki page at:

https://github.com/SudokuMonster/SukakuExplainer/wiki/Loading-Pencilmark-grids-into-Sukaku-explainer-(Test-Puzzles)

Which hopefully makes the issue of correct loading easier to digest and hopefully removes the ambiguity of the terms "Covered" and "Uncovered" cells.

**Comment by dobrichev** [comment] 2019-08-21 11:24
Well done on the wiki page!

I merged your code but still can't get what is the difference between your fix and 1..9's.
I would like to adjust later the one-line-per-puzzle batch loader to the rules.

**Closed** 2019-08-24 21:14 UTC
Labels: bug, enhancement
